### ISSUE TITLE
root 

### ISSUE THREAD

**Issue by ashrafalzyoud** [jcatrysse/redmine_parent_child_filters#2]
![Untitled](https://github.com/jcatrysse/redmine_parent_child_filters/assets/50211455/f9686521-350b-4dfc-a4cc-673d48940c9e)
thx for fast response and very good plugin
plz this our notes about plugin and its very nice if u added root because we have more than parent tracker
1-  translation missing: en.label_rootissue
2- if u can add root tracker
3- if u can add root status
@jcatrysse

**Comment by jcatrysse** [comment]
> 1- translation missing: en.label_rootissue 
> 2- if u can add root tracker 
> 3- if u can add root status

That should be ok now. But please verify because those new filters were a bit complicated 😅

**Comment by jcatrysse** [comment]
I made some more internal corrections, just pull again to be on the safe side.

**Comment by ashrafalzyoud** [comment]
I'm pull before 5 hours
Pull again are u make changes now?!!

**Comment by jcatrysse** [comment]
The last commit was 7 hours ago Commit: fd00b7debae2e1e67d4825a0b66fc656fc6a9ed1

**Comment by ashrafalzyoud** [comment]
perfect work
perfect plugin
