### ISSUE TITLE
parent parent task

### ISSUE THREAD

**Issue by ashrafalzyoud** [jcatrysse/redmine_parent_child_filters#3]
First of all, I thank you for your cooperation and quick response
in our project we have  four level with subtask
root tracker :- tender
parent parent tracker: wallet
parent tracker:  company
child tracker:     Paid
your plugin help me to contral that and filier it between levels
if i need search which paid from any wallet its hard its can be solved by added parent parent
**i hope  if u can added** 
1- parent parent tracker
2- parent parent status
I am so thankful you to  saved my life
@jcatrysse

**Comment by jcatrysse** [comment]
I will have a look, but probably not today… I'll keep you posted. Can this also be "a" parent filter as an extra? This wil anyway be a very slow and complicated filter :-) 

I can imagine something like "a" parent status = x

Not sure if negative filters will be very useable.

**Comment by ashrafalzyoud** [comment]
I think we added
parent.parent_id

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jcatrysse** [comment]
I made you an update, but this is not on the second or third parent, it is on any parent.

Commit: ffe4d6f0dcdc5a12189cef286521d3e9f3d6c204 

Already on master, so you can try and experiment a bit.

**Comment by jcatrysse** [comment]
Checkout the new release! Release: 0.0.5 (56fe60eb096a2d209d55a87abad930455c673c15) ...

It was a long day and night, but I think I managed to make you something.

**Comment by jcatrysse** [comment]
I added you some JavaScript to make the filter more intuitive, Disabling incompatible depths on `multiselect` filters.

Please reach out to me if the changes were useful.
